# Generated by Django 4.1 on 2023-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="position",
            field=models.CharField(
                choices=[("A", "chef"), ("B", "cook")], default="B", max_length=1
            ),
        ),
    ]
