# Generated by Django 4.1 on 2023-07-25 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_cook_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"ordering": ["position"]},
        ),
    ]
